#!/usr/bin/env bash
#
#    Copyright 2020 Jonathan Alfonso <alfonsojon1997@gmail.com>
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

if command -v git >/dev/null 2>&1 ; then
    echo "Dependency git is installed."
else
    echo "Dependency git is not installed. Please install it using your package manager"
fi

if command -v wget >/dev/null 2>&1 ; then
    echo "Dependency wget is installed."
else
    echo "Dependency wget is not installed. Please install it using your package manager"
fi

if command -v wine >/dev/null 2>&1 ; then
    echo "Dependency wine is installed."
else
    echo "Dependency wine is not installed. Please install it using your package manager"
fi

if command -v zenity >/dev/null 2>&1 ; then
    echo "Dependency zenity is installed."
else
   if command -v kdialog >/dev/null 2>&1 ; then
    echo "Dependency zenity is not installed. Using kdialog fallback."
   else
    echo "Dependency kdialog/zenity is not installed. Please install it using your package manager"
   fi
fi


roblox-install () {
	case $@ in
	install)
		if [[ ! -d "$WINEPREFIX/drive_c" ]]; then
			spawndialog question 'A working Roblox wineprefix was not found.\nWould you like to install one?'
			if [[ $? = "0" ]]; then
				rm -rf "$WINEPREFIX"
				# Make sure our directories really exist
				mkdir -p "$HOME/.local/share/wineprefixes"
				xdg-mime default "roblox-player.desktop" x-scheme-handler/roblox-player
				xdg-mime default "roblox-studio.desktop" x-scheme-handler/roblox-studio
				# Copy all our data files over, provided we're not being installed globally
				if [[ "$WRAPPER_DIR" != /usr/* ]]; then
					# Associate roblox-player and roblox-studio protocols
					printf "Installing Roblox protocols...\n"
					launchers_dest_dir="$HOME/.local/share/applications"
					handlers_dest_dir="$HOME/.rlw/handlers"
					mkdir -p "$handlers_dest_dir"
					install -v -m 755 $LIB_DIR/data/*.sh $handlers_dest_dir/
					install -v -m 755 $LIB_DIR/data/*.desktop $launchers_dest_dir/
					mkdir -p "$HOME/.local/share/icons/hicolor/scalable/apps"
					install -v -m 755 "$LIB_DIR/roblox.svg" "$HOME/.local/share/icons/hicolor/scalable/apps/"
					[[ "$?" = 0 ]] || {
						spawndialog error "An error occurred during protocol installation.\nSee terminal for more details (exit code $?)"
					}
				fi
				wget https://setup.rbxcdn.com/RobloxPlayerLauncher.exe -O /tmp/RobloxPlayerLauncher.exe
				chmod +x /tmp/RobloxPlayerLauncher.exe
				WINEDLLOVERRIDES="winemenubuilder.exe=" rwine /tmp/RobloxPlayerLauncher.exe
			else
				exit 1
			fi
		fi;;
	uninstall)
		spawndialog question 'This will remove Roblox entirely. Are you sure?'
		if [[ "$?" = "0" ]]; then
			xdg-desktop-menu uninstall "roblox.desktop"
			rm -f "$HOME/.local/share/applications/roblox-player.desktop"
			rm -f "$HOME/.local/share/applications/roblox-studio.desktop"
			rm -rf "$HOME/.local/share/icons/roblox.svg"
			rm -rf "$HOME/.local/share/icons/hicolor/scalable/apps/roblox.svg"
			rm -rf "$HOME/.rlw"
			"$WINESERVER" -k
			rm -rf "$WINEPREFIX"
			text='Roblox has been uninstalled successfully.'
			[[ "$WRAPPER_DIR" == /usr/* ]] && text+="\nTo uninstall Roblox Linux Wrapper and not just the Roblox Wineprefix, please use your package manager."
			spawndialog info "$text"
		fi;;
	*)
		spawndialog error 'How did you get here?';;
	esac
}


main () {
	rm -f $HOME/Desktop/ROBLOX*.lnk
	rm -rf "$HOME/.local/share/applications/wine/Programs/Roblox"
	if command -v zenity >/dev/null 2>&1 ; then
	sel=$(zenity \
		--title="$rlwversionstring" \
		--window-icon="$RBXICON" \
		--width=480 \
		--height=300 \
		--cancel-label='Exit' \
		--list \
		--text 'What option would you like?' \
		--radiolist \
		--column '' \
		--column 'Options' \
		FALSE 'Select Wine Release' \
		FALSE 'Wine Configuration' \
		FALSE 'Kill all Roblox processes' \
		FALSE 'Reinstall Roblox' \
		FALSE 'Uninstall Roblox' \
		FALSE 'Visit the GitHub page' 2>/dev/null )
	 else
	 sel=$(kdialog --title "$rlwversionstring" --radiolist 'What option would you like:' 1 'Select Wine Release' off 2 'Kill all Roblox processes' off 3 'Reinstall Roblox' off 4 'Uninstall Roblox' off 5 'Visit the GitHub page' off 2 >/dev/null )
	 fi
	
	case $sel in
	'Select Wine Release')
		printf '%b\n' "> rwineserver: killing wineserver"
		rwineserver -k
		winechooser
		main;;
	'Wine Configuration')
		rwine winecfg
		main;;
	'Kill all Roblox processes')
		spawndialog question 'This will forcefully close any game open. Are you sure?'
		if [[ $? -eq 0 ]]; then
			rwineserver -k
			if [[ $? -eq 0 ]]; then
				spawndialog info "Closed successfully."
			else
				spawndialog error "Could not close due to an error.\nThe game may already have been shut down."
			fi
		fi
		main;;
	'Reinstall Roblox')
		spawndialog question 'Are you sure you would like to reinstall?'
		if [[ "$?" = "0" ]]; then
			roblox-install uninstall; winechooser; roblox-install install; main
		else
			main
		fi;;
	'Uninstall Roblox')
		roblox-install uninstall
		exit;;
	'Visit the GitHub page')
		xdg-open https://github.com/roblox-linux-wrapper/roblox-linux-wrapper
		main;;
	esac
}

WRAPPER_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$WRAPPER_DIR"
if [[ "$WRAPPER_DIR" == /usr/* ]]; then
	# If we're in a path like /usr/bin, /usr/local/bin, etc., data resides in the corresponding share folder
	LIB_DIR=$(readlink -f "$WRAPPER_DIR/../share/roblox-linux-wrapper")
else
	LIB_DIR="$WRAPPER_DIR"
fi

if [ -f "$LIB_DIR/data/rlw-core.sh" ]; then
	printf "> main: Sourcing $LIB_DIR/data/rlw-core.sh\n"
	source "$LIB_DIR/data/rlw-core.sh"
else
	if command -v zenity >/dev/null 2>&1 ; then
		zenity \
			--no-wrap \
			--window-icon="$RBXICON" \
			--title="Roblox Linux Wrapper" \
			--error \
			--text="Missing rlw-core: try reinstalling rlw using the main script. If this problem presists, please report an issue to our GitHub page.\n" 2&> /dev/null	
	else
		 kdialog  --error "Missing rlw-core: try reinstalling rlw using the main script. If this problem presists, please report an issue to our GitHub page.\n"  --title "Roblox Linux Wrapper" 2&> /dev/null
	fi
    exit 1
fi

# Define some variables
man_args="-l rlw.6"
if [[ -d ".git" ]]; then
	rlwversion="$(git describe --tags)"
	git submodule init
	git submodule update
elif [[ "$WRAPPER_DIR" == /usr/* ]]; then
	rlwversion="$(cat $LIB_DIR/version)"
	man_args="rlw"
else
	rlwversion='version-unknown'
fi

rlwversionstring="Roblox Linux Wrapper $rlwversion"
printf '%b\n' "$rlwversionstring"

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
	man $man_args
	exit 0
elif [[ "$1" == "--version" || "$1" == "-v" ]]; then
	# We already print the version above, so we're okay
	exit 0
fi

# Don't allow running as root
if [ "$(id -u)" == "0" ]; then
	spawndialog error "Roblox Linux Wrapper will not run as superuser. Exiting."
	exit 1
fi

roblox-install install && main
