.TH rlw 6 2015\-05\-26
.SH NAME
rlw - Linux Wrapper for ROBLOX using Wine (Roblox Linux Wrapper)
.SH SYNOPSIS
\fBrlw\fR
.SH DESCRIPTION
Roblox Linux Wrapper (\fBrlw\fR) is a Linux Wrapper for ROBLOX using Wine. It does not implement any command line options, but rather a graphical selection screen with various options on start.
.SH "HOMEPAGE"
https://github.com/roblox-linux-wrapper/roblox-linux-wrapper
.SH "SEE ALSO"
WINE(1)
