.TH rlw 6 2016\-03\-02
.SH NAME
rlw - Linux Wrapper for ROBLOX using Wine (Roblox Linux Wrapper)
.SH SYNOPSIS
\fBrlw\fR \fIOPTION\fR
.SH DESCRIPTION
.PP
Roblox Linux Wrapper (\fBrlw\fR) is a Linux Wrapper for ROBLOX using Wine.
It does not implement any command line options other than \fB\-\-help/\-h\fR
and \fB\-\-version/\-v\fR, but rather a graphical selection screen with
various options on start.
.TP
\fB\-\-help/\-h\fR
display this help and exit
.TP
\fB\-\-version/\-v\fR
output version information and exit
.SH "HOMEPAGE"
https://github.com/roblox-linux-wrapper/roblox-linux-wrapper
.SH "SEE ALSO"
WINE(1)
